### ISSUE TITLE
Compare database to the schema.php file

### ISSUE THREAD

**Issue by CaptainQuirk** [CakeDC/migrations#162]
Hi there,

Could your plugin support direct modifications of the Schema.php file and do a comparison in the opposite direction ?

The workflow would then be, after having generated an initial Schema and migration:

* Make changes to the Schema.php file
* Run the __generate__ command that would
    + prompt for the direction of the comparison (from db to Schema, or inversely)
    + if database to Schema
       - Retrieve the database schema representation as « old » Schema
       - Compare it with the actual modified Schema.php
       - Generate a migration file
       - [ Add data  if needed  ] 
       - Update the database with the migration file

Thanks for this plugin anyhow. Couldn't work without it !

**Comment by omnuvito** [comment]
Hi @CaptainQuirk, you can check the feature in develop branch.
