### ISSUE TITLE
Problem with unique keys index in migration

### ISSUE THREAD

**Issue by tranfuga25s** [CakeDC/migrations#196]
When adding in the database an unique index for a text field with an specific key lenght the migration will fail.

Example:
This is generated by the plugin:
```
....
 public $migration = array(
        'up' => array(
            'create_field' => array(
                'products' => array(
                    'indexes' => array(
                        'products_code_unique' => array( 'column' => 'code', 
                                                          'unique' => 1, 
                                                          'length' => array('100' ) )
                    )
                )
            )
        ) ......
```
But the index definition is wrong ( at least for MySQL ), because the correct definition of the length of the index should be: 'length' => array( 'code' => '100').

This is fix come from reading line 646 of lib/Cake/Model/Datasource/Database/Mysql.php wich calls the function `_buildIndexSubPart` in line 691 wich expects the lenght element to be an array, not a single element.

**Comment by steinkel** [comment]
closed per #263
