### ISSUE TITLE
Schema updating after generation with plugins

### ISSUE THREAD

**Issue by tranfuga25s** [CakeDC/migrations#200]
When using `--plugin PluginName` in the command `generate`, the consoles tries to update the app schema file, not the schema for the plugin.

**Comment by rmwebs** [comment]
Reported this not long ago - fix for it is here: https://github.com/CakeDC/migrations/pull/198

It's available in the develop branch but not tagged into a stable version.

**Comment by deizel** [comment]
Should be fixed in latest release.
