### ISSUE TITLE
Is Migrations compatible with Cake 2.6.1?

### ISSUE THREAD

**Issue by lincolnbrito** [CakeDC/migrations#203]
When I run `./Console/cake` the migration shell is avaiable

When I run `./Console/cake Migrations.migration`

> $ ./Console/cake Migrations.migration

> Warning Error: include(c:\wamp\www\projeto\src\app\Plugin\Migration\Console\Command\MigrationShell.php): failed to open stream: No such file or directory in [C:\wamp\www\projeto\src\lib\Cake\Core\App.php, line 547]

> Warning Error: include(): Failed opening 'c:\wamp\www\projeto\src\app\Plugin\Migration\Console\Command\MigrationShell.
php' for inclusion (include_path='C:\wamp\www\projeto\src\app\Vendor/phpunit/php-text-template;C:\wamp\www\projeto\src\app\Vendor/phpunit/phpunit-mock-objects;C:\wamp\www\projeto\src\app\Vendor/phpunit/php-timer;C:\wamp\www\projeto\src\app\Vendor/phpunit/php-token-stream;C:\wamp\www\projeto\src\app\Vendor/phpunit/php-file-iterator;C:\wamp\www\modul
oweb\src\app\Vendor/phpunit/php-code-coverage;C:\wamp\www\projeto\src\app\Vendor/phpunit/phpunit;C:\wamp\www\projeto
\src\app\Vendor/symfony/yaml;C:\wamp\www\projeto\src\lib;.;C:\wamp\bin\php\php5.3.13\pear') in [C:\wamp\www\projeto\src\lib\Cake\Core\App.php, line 547]

> Error: Shell class MigrationShell could not be found.
#0 C:\wamp\www\projeto\src\lib\Cake\Console\ShellDispatcher.php(200): ShellDispatcher->_getShell('Migrations.migr...')
#1 C:\wamp\www\projeto\src\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->dispatch()
#2 C:\wamp\www\projeto\src\app\Console\cake.php(47): ShellDispatcher::run(Array)
#3 {main}**

**Comment by deizel** [comment]
It looks like `app\Plugin\Migration` should be `app\Plugin\Migrations` (note the added `s`).

**Comment by lincolnbrito** [comment]
OMG! ¬¬ 
Sorry for inconvenience
