### ISSUE TITLE
Feature Request: Bypass Cache When Introspecting Schema Changes

### ISSUE THREAD

**Issue by ojtibi** [CakeDC/migrations#205]
The built-in SchemaShell can directly introspect the database schema before generating schema.php. I was thinking it would be nice for the Migration plugin to do the same when it's checking for schema changes so we don't have to clear the table model caches before running the Migration `generate` command.

Additionally, maybe the Migration plugin can clear the cache after generating the migration file so the app doesn't have to expect the old table structure from the stale cache.

**Comment by andrej-griniuk** [comment]
Hi @ojtibi, 

Disabling cache before generating schema file and clearing cache after running migrations have been added and merged to develop branch.

Cheers,
Andrej
