### ISSUE TITLE
latest version throws exception saying schema table already exists

### ISSUE THREAD

**Issue by dogmatic69** [CakeDC/migrations#206]
There was no problem in 2.3.5, composer update to 2.3.6 and broken site.

**Comment by deizel** [comment]
Hi @dogmatic69, this sounds serious but I'm afraid I can't reproduce it here.

Can you check if either of these commits are the source of your problem? (bca17ea28f229decb9d417e16af8ed095ac991d7 or 894f736479b11586831fbcff94018d6922d943f2)

**Comment by drmonkeyninja** [comment]
@deizel I appear to be getting a similar issue to @dogmatic69. Commit bca17ea28f229decb9d417e16af8ed095ac991d7 looks to be the source of my problem. It occurs whenever I attempt to run migrations on a plugin following the examples from [the documentation](https://github.com/CakeDC/migrations/blob/master/Docs/Documentation/Examples.md).

**Comment by pmoraes** [comment]
Hi @drmonkeyninja, @dogmatic69, do you have this issue yet? Please let us know, otherwise we will close this issue.

Thanks.

**Comment by pmoraes** [comment]
Closing this issue, by anything let us know. Thank you.
