### ISSUE TITLE
Feature Request: Make -i mandatory when -c is specified

### ISSUE THREAD

**Issue by rchavik** [CakeDC/migrations#212]
It would be better to ask user to implicitly specify the migration connection (`-i`) argument when `-c` has been specified in the command line.

This prevents users running `down` on a `test` connection and finding the tables has been dropped on the `default` connection.

**Comment by deizel** [comment]
Thanks, should be fixed by #219.

**Comment by rchavik** [comment]
Wow.

Thank you so much @waldemarnt and @CakeDC  !
