### ISSUE TITLE
Migrations fails with CakePHP >= 2.6.6

### ISSUE THREAD

**Issue by rbrouwer** [CakeDC/migrations#213]
In CakePHP 2.6.6 something was changed in the Inflector of CakePHP.

After this the following error appears when migrating using this plugin:
>me@server:~$ ./Vendor/bin/cake Migrations.migration run all
>Cake Migration Shell
>---------------------------------------------------------------
>Running migrations:
>An error occurred when processing the migration:
>Migration:
>Error: Migration precheck class (Migrations.PrecheckException) could not be loaded.

This seems to happen because it tries to load the precheckException class instead of the PrecheckException. On a case-sensitive filesystem this minor difference causes the error quoted above.

**Comment by okinaka** [comment]
cakephp's bug?

**Comment by CakeDC** [comment]
Hi, this is fixed now

https://github.com/CakeDC/migrations/releases/tag/2.3.7
