### ISSUE TITLE
Parameter for comparing to the schema.php

### ISSUE THREAD

**Issue by ravage84** [CakeDC/migrations#221]
It's rather repetitive to answer the question ``Do you want compare the schema.php file to the database?``.
So, it would be nice if there was a parameter to this, e.g. ``--compare``.

So instead of executing ``console\cake.bat Migrations.migration generate -f``  (on Windows) and then have to answer a question I know the answer to already, I would execute ``console\cake.bat Migrations.migration generate -compare -f``. This would help me to DRY.

This makes especially sense if you prepare such commands in your IDE or in an automation tool, such as ANT.

Related Shell code:
https://github.com/CakeDC/migrations/blob/2.4.0/Console/Command/MigrationShell.php#L427-L436

**Comment by ravage84** [comment]
Related: #220

**Comment by andrej-griniuk** [comment]
--compare parameter has been added and merged to develop branch.
