### ISSUE TITLE
Shell command to skip/jump to certain migration version

### ISSUE THREAD

**Issue by ravage84** [CakeDC/migrations#223]
For the second time, we implemented the Migrations plugin long after the prjoject started, in one case even after the project launched to production.
So we created an initial migration script for all the already existing tables.

But we couldn't run the the migration in production, since we couldn't just reset the whole DB to satisfy the Migration shell.
We then had to tweak the ``schema_migrations`` table by creating it and filling it up with all migration versions including the initial schema creation that were done manually up to this point.

For example:
```` sql
/*
Create the Schema Migrations Table
*/
CREATE TABLE `schema_migrations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `class` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*
Pre-fill Schema Migrations Table to skip to current state
*/
INSERT INTO `schema_migrations` (`id`,`class`,`type`,`created`) VALUES (1,'InitMigrations','Migrations','2015-07-06 13:49:46');
INSERT INTO `schema_migrations` (`id`,`class`,`type`,`created`) VALUES (2,'ConvertVersionToClassNames','Migrations','2015-07-06 13:49:46');
INSERT INTO `schema_migrations` (`id`,`class`,`type`,`created`) VALUES (3,'IncreaseClassNameLength','Migrations','2015-07-06 13:49:46');
INSERT INTO `schema_migrations` (`id`,`class`,`type`,`created`) VALUES (10,'InitialSchemaCreation','app','2015-07-06 18:40:19');
````

It would be nice to have a shell command to "skip" or "jump" to a cetain migration version.
This means it doesn't actually run the migration, but saves all skipped migration versions into the ``schema_migrations`` table just as if it would do normally.

This could look like this on Windows:
``console\cake.bat Migrations.migration skip-to {version}``

May be we use the word __warp__? :rocket:

**Comment by Megslalk** [comment]
Closing issue - Feature has been merged. Please re-open or create a new issue should you require further assistance, thanks!

**Comment by ravage84** [comment]
Cool stuff! The next release will have some neat features :smirk_cat: 

But I think it would have been even better if one could use the timestamp only.

So instead of:
````
cake Migrations.migration run all --skip 1458963215_articles_table
````
The following would suffice:
````
cake Migrations.migration run all --skip 1458963215
````

https://github.com/omnuvito/migrations/blob/be0922a4a2f02ec6cb2af830beb3d8540cd3eebc/Docs/Documentation/Examples.md#skipping-certain-migrations

@Megslalk & @pmoraes what do you think?

**Comment by pmoraes** [comment]
Hi @ravage84, This is good as well. But I think that just the timestamp the chance to skip the wrong version is high. What do you think?

**Comment by ravage84** [comment]
That might be true, I just think of a situation where I want to skip quite a few migrations.

That's why I asked for a function to **jump to** a given timestamp.

Let's say I have 50 migrations and due to some database hickup, I want to skip the first 20, since my db is actually in the state of the 20th migration.

That would mean I had to enter the full name of 20 migrations.

Probably this should be solved with an additional commnand option like ``--first {timestamp/migration name}``

To skip the fist 20 migrations (a.k.a. "jump to" the 21. migration), I would enter:

````
cake Migrations.migration run all --first 1458963215_articles_table
````

That could be combined with the skip option:

````
cake Migrations.migration run all --first 1458963215_articles_table --skip 1458967215_some_migratoin_way_after_articles_table
````

**Comment by pmoraes** [comment]
Hi @ravage84  Really this would be a good feature I think. Could you open a new issue asking to develop this feature? Then I can put it in my desk and work on it.

Thanks.

**Comment by ravage84** [comment]
Sure can... This release is gettting even better! :smirk_cat:

**Comment by pmoraes** [comment]
NIce, Thank you.
