### ISSUE TITLE
Migrations with ; character in comments generate a SQL Syntax Error.

### ISSUE THREAD

**Issue by felipefrancisco** [CakeDC/migrations#224]
Tried to execute a migration with a `;` in the comments of my `CREATE TABLE`instruction and I got a Syntax Error. I guess this should be escaped during the migration execution.

**Comment by steinkel** [comment]
Could you please paste your migration here or in a gist for checking?

Thank you!

**Comment by omnuvito** [comment]
Hi @felipefrancisco, let's close this issue. It has long since We made the request about your migration for the review. If you still have this problem, let us know and we can reopen it.
