### ISSUE TITLE
how to define multiple migration

### ISSUE THREAD

**Issue by SamMnrve** [CakeDC/migrations#245]
We currently have several version of the same application cakephp 1.3, and we migrated to cakephp2.

how migration scheme
  - The client 1 of the version 1 to 2
  - The client 2 of the version 1.2 to 2
  - The client 3 of the 1.5 Version 2

it's possible to defined many path to migrate

000_to_001_xxxxxxx.php
001_to_002_xxxxxxxxxx.php

0000_to_0001_xxxxxx.php
0001_to_0002_xxxxxx.php

etc or an other method.

thx

**Comment by pmoraes** [comment]
Hi @SamMnrve , could you to be more clear with your doubt? 

Thanks.

**Comment by SamMnrve** [comment]
Hi @pmoraes 

I wonder if it is possible to define several migration scenario.

I have several customers who each have a version of the product.

we made a migration cakephp2 and we would apply for every customer a migration scenario. (As in the examples map.php file but I can not find any example of creating this file).

example:
migration_client1.php
        with in the list of migration to perform for the client 1.

migration_client2.php
        with in the list of migration to perform for the client 2.

sorry for the English is that google translated. :(


Thanks

**Comment by pmoraes** [comment]
Hi @SamMnrve, so I was thinking here and talking with cakedc team about that. you having the same code to different database, you'll have a big chance to break your application. 
What do you think, separate your application in some branches? 

Let us know if this can help you. 

Thanks

**Comment by ravage84** [comment]
@SamMnrve I agree with @pmoraes, your problem/needs go way beyond what the Migrations plugin provides and should provide.

You have a rather organisational problem, than an programmatic one.

Not sure if your different customers with their different versions of your (hopefully unified) application have different database layouts, which I don't hope.
But I recommend you to look into unifying your code base and your database schema.

Then you can use plugins to extend certain functionality for one customer without hacking your "core application".
After that your database migrations can be written once and used everywhere.
