### ISSUE TITLE
How can I run migrations programmatically?

### ISSUE THREAD

**Issue by BassemN** [CakeDC/migrations#254]
Hi,

Great plugin!
How can I run migrations programmatically via an installer script.I cant see this into docs?

Thanks

**Comment by BassemN** [comment]
Hi,
Cab you please help me on this issue?

**Comment by rchavik** [comment]
See https://github.com/croogo/croogo/blob/master/Extensions/Lib/CroogoPlugin.php#L373-L408 on how croogo does it

**Comment by pmoraes** [comment]
Hi @BassemN, do you have this doubt yet? What @rchavik told, solve your problem?

**Comment by BassemN** [comment]
Yes, Thanks to @rchavik
