### ISSUE TITLE
Error "Cannot use 'String' as class name as it is reserved"

### ISSUE THREAD

**Issue by Back-Sephiroth** [CakeDC/migrations#259]
Hi,

I've got a problem when i run the migration, i've this message :

> Cannot use 'String' as class name as it is reserved in lib/Cake/Utility/String.php on line 26

I use Cake 2.8.3 on PHP7

Thanks for your help

**Comment by omnuvito** [comment]
Hi @Back-Sephiroth, String is a reserved word in PHP7. This was resolved already and the solution is available right now in the develop branch. You can check it and let us know if the solution solved your issue.
