### ISSUE TITLE
MySQL constraint 

### ISSUE THREAD

**Issue by cakeEaterPHP** [CakeDC/migrations#261]
Hello,

I've got a issue with your plugin when I adda product with some tags, 
sometime I'have a SQL error not always

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '%TheGeneratedKey%' for key 'UNIQUE_TAGGING

**Comment by pmoraes** [comment]
Hi @cakeEaterPHP, could you give more information for us?
Putting some use cases would be great too.

Waiting for your response to help you.

**Comment by pmoraes** [comment]
Hi @cakeEaterPHP, we are closing this issue. By anything let us know.

Thanks,
