### ISSUE TITLE
Question: why does the doc says one need to drop a field when altering its indexes?

### ISSUE THREAD

**Issue by stripthis** [CakeDC/migrations#264]
Hi there,

In the documentation it is said "if you want to drop an index, then you need to drop the field including the indexes you want to drop, then create the field again.". 
```
'drop_field' => array(
    'posts' => array(
        'title',
        'indexes' => array(
            'UNIQUE_TITLE'
        )
    )
),
'create_field' => array(
    'posts' => array(
        'title' => array(
            'type' => 'string',
            'null' => true,
            'length' => 255
        )
    )
)
```

I have tried to do that without droping the field (as to not have to drop the data in this field), and it seems to work. 
```
'drop_field' => array(
    'posts' => array(
        'indexes' => array(
            'UNIQUE_TITLE'
        )
    )
)
```

Since the documentation seems to be saying don't do that but on the other hand it seems to works, I'm wondering if it's because there are known issue with certain database system, etc. Thanks for you time!

**Comment by andrej-griniuk** [comment]
Hi @stripthis,

Thanks for reporting, you're right. Docs updated.

Cheers,
Andrej
