### ISSUE TITLE
Shell command to jump to certain migration version

### ISSUE THREAD

**Issue by ravage84** [CakeDC/migrations#272]
Let's say I have 50 migrations and due to whatever reason, I want to skip the first 20 migrations.
E.g. my DB is actually in the state of the 20th migration.

Probably this should be solved with an additional commnand option like ``--first {timestamp/migration name}``

To skip the fist 20 migrations (a.k.a. "jump to" the 21. migration), I would enter:

````
cake Migrations.migration run all --first 1458963215_articles_table
````

That could be combined with the skip option:

````
cake Migrations.migration run all --first 1458963215_articles_table --skip 1458967215_some_migratoin_way_after_articles_table
````

An alternative name for this option could be ``--jump-to``

Refers:
https://github.com/CakeDC/migrations/issues/223#issue-93513074
https://github.com/CakeDC/migrations/issues/223#issuecomment-236144544
https://github.com/CakeDC/migrations/issues/223#issuecomment-236215271

**Comment by steinkel** [comment]
Merged into develop. Thanks!
