### ISSUE TITLE
Class 'Object' not found

### ISSUE THREAD

**Issue by ravage84** [CakeDC/migrations#274]
Tried to run my migrations on a PHP 7 environment.

It failed with the following message:

````
Cake Migration Shell
---------------------------------------------------------------
Running migrations:
PHP Fatal error:  Class 'Object' not found in /var/www/html/Plugin/Migrations/Lib/CakeMigration.php on line 17

Fatal error: Class 'Object' not found in /var/www/html/Plugin/Migrations/Lib/CakeMigration.php on line 17
Fatal Error Error: Class 'Object' not found in [/var/www/html/Plugin/Migrations/Lib/CakeMigration.php, line 17]
````

``Object`` is a reserved word as of PHP 7:
http://php.net/manual/en/reserved.other-reserved-words.php

It is used in https://github.com/CakeDC/migrations/blob/5238a8a995f1392ea5dac3db726d294b6b2bc7dc/Lib/CakeMigration.php#L17

The CakePHP core fixed that by renamit (& aliasing it) it to ``CakeObject`` in https://github.com/cakephp/cakephp/blob/7207d8f16a1cf2ba7e5932fb2e7941a87e53e5e6/lib/Cake/Core/Object.php#L17-L18

**Comment by steinkel** [comment]
Closed per #275
