### ISSUE TITLE
Change of string column length to 255 detected but not executed

### ISSUE THREAD

**Issue by ravage84** [CakeDC/migrations#288]
This is a follow up issue of #233.

Yesterday we updated two projects from CakePHP 2.7.x to 2.9.1 and CakeDC/Migrations 2.4.x to 2.5.0.

It looks as if the bug mentioned in #233 is actually fixed as changing a string column from anything to 255 on a MySQL DB now gets detected and thus the migration gets generated.

```` php
	public $migration = array(
		'up' => array(
			'alter_field' => array(
				'items' => array(
					'productivity_stage' => array('type' => 'string', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'comment' => 'comment'),
				),
			),
		),
		'down' => array(
			'alter_field' => array(
				'items' => array(
					'productivity_stage' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 20, 'collate' => 'utf8_general_ci', 'comment' => 'comment'),
				),
			),
		),
	);
````

But now, when you execute this migratrion script on a different host or run down and run up again, the column is still as before (of 20 characters in the example case).

**Comment by CakeDCTeam** [comment]
I will check as soon as possible.

**Comment by ravage84** [comment]
Did you find anything, yet?
Can I help you with anything?

**Comment by ravage84** [comment]
So, is this fixed? I see commit https://github.com/andrej-griniuk/cakedc-migrations/commit/1b076a0a54e91c7ba05ed0bb5e876f9d6b0a00ff

**Comment by andrej-griniuk** [comment]
Hi @ravage84 

unfortunately no, wasn't as easy as I thought. Will probably require a patch to the core CakeSchema class again, but didn't have a chance to look into it deeper again.

**Comment by skie** [comment]
As recomendation would be define `'length' => 255` in such cases.
