### ISSUE TITLE
Invalid translation

### ISSUE THREAD

**Issue by odan** [CakeDC/migrations#289]
https://github.com/CakeDC/migrations/blob/e41c7d292758dd67f1833203f35a7dd251f12a32/Console/Command/MigrationShell.php#L183

Expected:
'help' => __d('migrations', 'Skip certain migration.')))

https://github.com/CakeDC/migrations/blob/e41c7d292758dd67f1833203f35a7dd251f12a32/Console/Command/MigrationShell.php#L186

Expected: 
'help' => __d('migrations', 'Jump to a certain migration and mark the preceding migrations as executed.')))

**Comment by ravage84** [comment]
The translation domain is missing.

http://api.cakephp.org/2.9/function-__d.html

**Comment by andtxr** [comment]
Thank you guys!
