### ISSUE TITLE
Compare database to schema.php not documented

### ISSUE THREAD

**Issue by ravage84** [CakeDC/migrations#290]
A colleague of mine, @odan, asked me, what the difference between **"Do you want to compare the schema.php file to the database?"** and **"Do you want to compare the database to the schema.php file?"** is.

I wanted to point him to the documentation, but found none.
So, I guess this should be properly documented.

Am I right, that you can either use the (changed) schema.php or the (changed) database as means to compare it to the other and generate a migration script from that?

**Comment by pmoraes** [comment]
Hi @ravage84 it's was fixed and merged.
