### ISSUE TITLE
Migration Generation Automation

### ISSUE THREAD

**Issue by ravage84** [CakeDC/migrations#291]
I thought about fully automating the generation of migration scripts or at least autome as much as possible.

So after adding the ``--compare`` parameter for comparing to the schema.php in #221 and adding the ``--overwrite`` paramater for overwriting the schema.php in #220, there are only two manual steps left to generate a migration script, which cannot be provided by the CLI right now:

1.  Answering the question "Do you want to preview the file before generation?"  https://github.com/CakeDC/migrations/blob/2.5.0/Console/Command/MigrationShell.php#L643
1. Entering a migration script name https://github.com/CakeDC/migrations/blob/2.5.0/Console/Command/MigrationShell.php#L672

Thus, I propose three new parameters:

1. ``--no-preview`` to disable the preview
1. ``--preview`` for showing the preview
1. ``--name XYZ`` to provide a migration script name

**Comment by andtxr** [comment]
👍 from me. I will discuss with others.

**Comment by pmoraes** [comment]
Hi @ravage84, it already was merged. Closing this issue. Thanks.

**Comment by ravage84** [comment]
@CakeDC cool guys.
Thanks! 🍻
