### ISSUE TITLE
It's possible to use migrations for custom plugin?

### ISSUE THREAD

**Issue by ricardovigatti** [CakeDC/migrations#312]
I've tried to put it like the example below and run ```cake Migrations.migration run up```, but i got a message saying that i have no valid migration files.

    [ ... ]
    /Plugin
        /Custom
            /Config
                /Migration
                    001_add_custom.php
            /Controller
            /Model
            /View
    [ ... ]

**Comment by pmoraes** [comment]
I'm not sure about your question. Could you give more information about it? 

Thanks @ricardovigatti

**Comment by ricardovigatti** [comment]
Well, there is nothing special about this. I want to use migrations whitin custom plugins.

I've tried like the example above, putting the generated migration file inside the plugin folder, but got that error. Seems like the Migrations plugin didn't find the migration inside the plugin folder.

**Comment by pmoraes** [comment]
you can have migrations inside the plugins. You can check our documentation. [https://github.com/CakeDC/migrations/blob/master/Docs/Documentation/Examples.md#running-migrations-for-plugins](url) if you have any more doubts, please let me know.

**Comment by ricardovigatti** [comment]
Well, i was searching for a doc like that, but somehow the link you gave is pointing me to a 404 not found page.

**Comment by rchavik** [comment]
Try https://github.com/CakeDC/migrations/blob/master/Docs/Documentation/Examples.md#running-migrations-for-plugins

**Comment by ricardovigatti** [comment]
Thanks, i'll try it
