### ISSUE TITLE
Create field after/before another

### ISSUE THREAD

**Issue by ricardovigatti** [CakeDC/migrations#313]
Is it possible to create fields after or before another?

Example, if i have: id, name, created, updated

Now i want to add a new field "value" between name and created. So the final expected structure will be: id, name, value, created, updated.

Thank you.

**Comment by pmoraes** [comment]
Hi @ricardovigatti.

Yes. It's possible, you just need to use a param called "after". Like that 

'value' => ['type' => 'string', 'length' => 300, 'null' => false, 'after' => 'name']

**Comment by ricardovigatti** [comment]
Thank you
